### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by brandon-reinhart**

### CODE REVIEW

**Comment by brandon-reinhart** [comment]
Request to update dep on glam to keep pace with Bevy 0.8

**Review by bonsairobo — APPROVED** [review]

**Comment by bonsairobo** [comment]
Thank you!

**Comment by brandon-reinhart** [comment]
> Thank you!

No prob. If you get a chance to push an updated crate, I'd be much obliged.

**Comment by bonsairobo** [comment]
> > Thank you!
> 
> No prob. If you get a chance to push an updated crate, I'd be much obliged.

Just published v0.2.0

**Pull request merged**
